### ISSUE TITLE
JCommentPart#escape(String) may fail with StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by schwitzkroko** [highsource/jaxb2-basics#122]
When we xjc-generate java code based on a xsd we encounter a case where text content of a 'xs:documentation' element ends with an asterisk char. A StringIndexOutOfBoundsException makes the execution fail.
From checking the JCommentPart#escape(String) code i assume the expectation here is, that such an occurance is always terminated with a slash (javadoc-like?). 
I don´t think this expectation can always be met. I suggest that a check on the string length is introduced before trying 's.charAt(i+1)'.

```
...
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
... 40 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 717
at java.lang.String.charAt(String.java:658)
at com.sun.codemodel.JCommentPart.escape(JCommentPart.java:133)
at com.sun.codemodel.JCommentPart.format(JCommentPart.java:95)
at com.sun.codemodel.JDocComment.generate(JDocComment.java:150)
at com.sun.codemodel.JFormatter.g(JFormatter.java:320)
at com.sun.codemodel.JEnumConstant.declare(JEnumConstant.java:134)
at com.sun.codemodel.JFormatter.d(JFormatter.java:346)
at com.sun.codemodel.JDefinedClass.declareBody(JDefinedClass.java:787)
at com.sun.codemodel.JDefinedClass.declare(JDefinedClass.java:774)
at com.sun.codemodel.JFormatter.d(JFormatter.java:346)
at com.sun.codemodel.JFormatter.write(JFormatter.java:420)
at com.sun.codemodel.JPackage.build(JPackage.java:422)
at com.sun.codemodel.JCodeModel.build(JCodeModel.java:328)
at com.sun.codemodel.JCodeModel.build(JCodeModel.java:318)
at com.sun.tools.xjc.XJCBase._doXJC(XJCBase.java:817)
at com.sun.tools.xjc.XJCBase.doXJC(XJCBase.java:755)
at com.sun.tools.xjc.XJCBase.execute(XJCBase.java:654)
at com.sun.tools.xjc.XJC2Task.execute(XJC2Task.java:25)
at org.jvnet.jaxb2_commons.xjc.XJC2Task.execute(XJC2Task.java:35)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
...
```

**Comment by schwitzkroko** [comment]
sorry, please close, this was meant to go to jaxb-ri... :-/
